apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "backend.fullname" . }}
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  gateways:
  - mesh
  hosts:
  - {{ include "backend.fullname" . }}.{{ .Values.namespaceOverride | default .Release.Namespace }}.svc.cluster.local
  http:
  - retries:
      attempts: 3
      perTryTimeout: 2s
    route:
    - destination:
        host: {{ include "backend.fullname" . }}.{{ .Values.namespaceOverride | default .Release.Namespace }}.svc.cluster.local
        port:
          number: {{ .Values.service.port | default 8080 }}
      weight: 100